language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
node_js: "11.5"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
  - master

before_script:
 - npm install -g @angular/cli

script:
  - cd backend
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - ./mvnw test -B
  - cd ../frontend
  - npm install
  - ng test --watch=false --browsers=ChromeHeadless
