language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk11
dist: trusty

addons:
  chrome: stable

cache:
  directories:
     - ./frontend/node_modules

branches:
  only:
  - master

before_script:
 - nvm install 11.6
 - nvm use 11.6
 - npm install -g @angular/cli

env:
  - MAYPAD_HOME=/home/travis/build/maypad/maypad/backend

script:
  - cd backend
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - ./mvnw test -B
  - cd ../frontend
  - npm install
  - ng lint
  - ng test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - ng e2e -- --protractor-config=e2e/protractor-ci.conf.js
