language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
node_js: "11.5"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./frontend/node_modules

branches:
  only:
  - master

before_script:
 - npm install -g @angular/cli

script:
  - cd backend
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - ./mvnw test -B
  - cd ../frontend
  - npm install
  - ng test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - ng e2e -- --protractor-config=e2e/protractor-ci.conf.js
